services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./tools:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_USER=me
      - POSTGRES_DB=trucode
    networks:
      - my_network
  migrator:
    build:
      context: ./migrator
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=me
      - DB_PASSWORD=supersecret
      - DB_NAME=trucode
    networks:
      - my_network
    restart: on-failure
    depends_on:
      - db
  app:
    build:
      context: ./app
    ports:
      - 80:8080
    networks:
      - my_network
    restart: on-failure
    depends_on:
      - api
  api:
    build:
      context: ./api
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=me
      - DB_PASSWORD=supersecret
      - DB_NAME=trucode
    networks:
      - my_network
    restart: on-failure
    depends_on:
      - db

networks:
  my_network:
    driver: bridge