###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "username":"Wens2",
  "password":"12345"
}


###
POST http://localhost:3333/auth/register
Content-Type: application/json

{
  "username":"Wens2",
  "password":"12345",
  "firstname":"Wens",
  "lastname":"Neurete",
  "email": "wens@gmail.com"
}
