
###
GET http://localhost:3333/persons?education=HS-grad,9th,Doctorate,12th,Assoc-acdm,Some-college&marital_status=Married-civ-spouse&occupation=Craft-repair
Authorization: Beaber eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZWF0IjoxNzMyMjI3Mjk3LCJpYXQiOjE3MzIyMjY2OTcsImlkIjo0fSwic2Vzc2lvbiI6ImE4MDMyNzZiLTZhZGItNTJiYy1hMTNiLTJjMTA1ZDdlODhhMiIsInNlYXJjaF9maWx0ZXJzIjoiIn0.eKsoWH6HEEKFOxZA1yTNKMrAWRKNDEns84HtdTHhhyg
